-- Purpose: Infrastructure smoke table for the Oracle AI Lab.
-- LAB_SMOKE_TEST is not release-management functionality. It exists only to
-- prove that managed install, SQL smoke tests, review, and packaging can target a
-- versioned DB object.

set echo off
set feedback on
set heading on
set verify off
whenever sqlerror exit sql.sqlcode

prompt Creating infrastructure smoke table AI_APP_OWNER.LAB_SMOKE_TEST.

create table AI_APP_OWNER.LAB_SMOKE_TEST (
  ID number generated by default as identity not null,
  CREATED_AT timestamp default systimestamp not null,
  MESSAGE varchar2(200 char) default 'Infrastructure smoke object' not null,
  constraint LAB_SMOKE_TEST_PK primary key (ID)
);
